services:
    Aurelienazerty.siteNotification.notification.type.sample:
        class: Aurelienazerty\siteNotification\notification\type\sample
        shared: false # service MUST not be shared for this to work!
        parent: notification.type.base
        calls:
            - [set_controller_helper, ['@controller.helper']]
        tags:
            - { name: notification.type }
