imports:
    - { resource: notifications.yml }
services:
    aurelienazerty.sitenotification.listener:
        class: aurelienazerty\sitenotification\event\listener
        arguments:
            - '@dbal.conn'
            - '@user'
            - '@language'
        tags:
            - { name: event.listener }
